### ISSUE TITLE
有些问题想向您请教

### ISSUE THREAD

**Issue by YangYuchi11** [Sh-Fang/TRIC-reproduction#1]
能否获取您的联系方式与您交流下呢?这方面有些问题想向您请教

**Comment by Sh-Fang** [comment]
可以的话就在这里问吧

**Comment by YangYuchi11** [comment]
那个output文件是在哪生成的

**Comment by Sh-Fang** [comment]
output文件算是一个GroundTruth，并不是我自己生成的，是数据对应的正确的匹配结果

**Comment by YangYuchi11** [comment]
还有个问题就是代码有没有避免自同构的功能啊 有的话是哪个地方呀

**Comment by Sh-Fang** [comment]
代码没有考虑自同构的功能，目前Data文件夹中包含的Query都不是自同构的
